### ISSUE TITLE
Checkbox hover

### ISSUE THREAD

**Issue by lingtalfi** [lokesh-coder/pretty-checkbox#24]
Hi, I'm using a link into the markup, like so:

```
     <div class="pretty p-default p-curve">
                        <input type="checkbox" />
                        <div class="state ">
                            <label>
                                <a href="#">Paris</a>
                            </label>
                        </div>
      </div>
```

The only problem I have is that when I hover the link, the css hover event doesn't seem to fire.
So my css rule doesn't work:

```
a:hover{
     text-decoration: underline;
}
```

Can I fix it using css only?
(I suppose I could find a workaround with js, but I'm interested to know if a css only solution
has been found already)

**Comment by lingtalfi** [comment]
I found it, just simple css: it was the input that covered the link, changing this:

```css
.pretty input {
    min-width: 1em;
    width: 100%;
}
```


to this:
```css
.pretty input {
    min-width: 0;
    width: auto;
}
```

fixes my problem.
Issue solved.
