### ISSUE TITLE
Reverse input and label positioning?

### ISSUE THREAD

**Issue by jbdivups** [lokesh-coder/pretty-checkbox#34]
Trying to have label on left and radio input on right. Any help is much appreciated. Thanks for the great library.

**Comment by lokesh-coder** [comment]
Hi @jbdivups ,

Plesae try this CSS,

```css
.pretty .state label{
  padding-right: 1.5rem;
  text-indent: inherit;
}

.pretty .state label:after,
.pretty .state label:before{
  left: auto;
  right: 0;
}
```

Also, here's the jsbin,
https://jsbin.com/mikuqil/edit?html,css,output
