### ISSUE TITLE
Set background color of checkbox when not ticked

### ISSUE THREAD

**Issue by Andruschenko** [lokesh-coder/pretty-checkbox#40]
I saw that you're working on a new version right now. Therefore I won't file a PR which might collide with your work but add this so that others might benefit from it and you might add this in the new version:

In the current version of the package, the background color can't be changed via a variable.

Perhaps you want to expose the following so it can be modified! Here I change the background-color of the checkbox to `lightgrey`:

```css
.pretty .state label:before {
      background-color: lightgrey;
}
```
