### ISSUE TITLE
How to see if checkbox has tab focus

### ISSUE THREAD

**Issue by benny-chen-mpf** [lokesh-coder/pretty-checkbox#55]
The default checkbox/radio button shows/hides a border around the control when you tab in and out of it. Pretty-checkbox controls doesn't show this, so I have no idea which control has the focus. Is there a way to enable this?

**Comment by lokesh-coder** [comment]
Hi @benny-chen-mpf
So, you want that focused border as a class? 

Righ now the border will be there only for tab focus as you mentioned.

**Comment by benny-chen-mpf** [comment]
Hey @lokesh-coder,
A class would be great. Right now I'm not seeing any border when a pretty-fied control gets focus.

**Comment by tonypeng** [comment]
following this as well 👍

**Comment by Chewieez** [comment]
I'm currently having this same issue. We are using radio buttons styled with pretty-checkbox and when I tab through, the toggles are not showing that they have the current focus. I can use the arrow keys to select radio button states, so focus is on the correct element, but there is not visual indication that focus is on the radio buttons. Thanks!

**Comment by rbonomo** [comment]
```css
<style>
    .pretty input[type="checkbox"]:focus + .state:before {
        border-color: #66afe9;
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 4px rgba(102,175,233,.6);
    }
    .pretty.p-switch .state:before {
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    }
</style>
```
This will give your switches a nice Bootstrap 3 input focus look.
