### ISSUE TITLE
SVG icon is missing in indeterminate state

### ISSUE THREAD

**Issue by guanzo** [lokesh-coder/pretty-checkbox#57]
Reproduction: https://jsfiddle.net/guanzo/76xesvct/12/

The 2 checkboxes are exactly the same, except the first one is using `p-icon` and `icon`, while the second one is using `p-svg` and `svg`.

I believe the problem is here: https://github.com/lokesh-coder/pretty-checkbox/blob/3a949d30497aae3bce044f32fcd91da87e4813bf/src/scss/states/_indeterminate.scss#L6-L14

It needs to be
```scss
input[type='checkbox']:indeterminate ~.state.p-is-indeterminate {
    display: block;

    .icon, .svg {
      display: block;
      opacity: 1;
    }
  }
```
