### ISSUE TITLE
SVG icon fill and stroke specific color options

### ISSUE THREAD

**Issue by penuts7644** [lokesh-coder/pretty-checkbox#61]
Hi,

I was wondering if it is possible to separate the color options based on `fill` and `stroke` attributes of SVG icons. As of now the five color options (like `p-success` and `p-success-o`) use the `color` and `stroke` attributes.

So besides having only having classes like:
```css
.p-success {
    color: <value>;
    stroke: <value>;
}
```

Also have classes for:
```css
.p-fill-success {
    color: <value>;
    fill: <value>;
}
```

Cheers, Wout
