### ISSUE TITLE
always p-pulse

### ISSUE THREAD

**Issue by chadsteele** [lokesh-coder/pretty-checkbox#62]
Thank you @lokesh-coder - great tool!

Is there a way to get it to pulse on every click?  I tried moving **p-pulse** from the parent class to the state, but it doesn't work...

```
            <div class="pretty p-icon p-round p-toggle ">
              <input type="checkbox" />
              <div class="state p-info p-on **p-pulse**">
                <i class="icon fa fa-arrow-down"></i>
                <label>Descending</label>
              </div>
              <div class="state p-info p-off **p-pulse**">
                <i class="icon  fa fa-arrow-up"></i>
                <label>Ascending</label>
              </div>
            </div>
```

**Comment by lokesh-coder** [comment]
Hi @chadsteele ,

Actually reverse animation feature is not yet available. 😞 But, you can try this code,

```css
.pretty.p-pulse:not(.p-switch) input:not(:checked)~.state label:before {
    animation: pulseBack 1s;
}

@keyframes pulseBack {
    from {
        box-shadow: 0 0 0 1.5em rgba(189,195,199,0);
    }

    to {
        box-shadow: 0 0 0 0 #bdc3c7;
    }
}

```
