### ISSUE TITLE
Disabled Checkbox Label is gray.

### ISSUE THREAD

**Issue by dowanx** [lokesh-coder/pretty-checkbox#8]
I love your library and spent most of today implementing it :) 

That being said there is one aspect I can't seem to figure out.  When disabling a checkbox I only want the checkbox, <i class="mdi mdi-check"></i>, to gray out, but not the rest of the label.  

Is there a way to do this?  If not is it possible for it to simply have none of it gray out?

**Update**  **Answer** 

Go figure as soon as I post this I come up with the answer ;)

The following CSS removes the gray completely, however it would be nice if the checkbox portion was still grayed out. 

input:disabled+label{   
   opacity : 1 !important;
   filter  : alpha(opacity=1) !important; /* IE<9 */   
}

The following CSS removes the gray from just the <i> tag, and keeps the rest of the label normal

input:disabled+label{
   opacity : 1 !important;
   filter  : alpha(opacity=1) !important; /* IE<9 */
}

input:disabled+label i{
   opacity : .5 !important;
   filter  : alpha(opacity=50) !important; /* IE<9 */
}

**Comment by lokesh-coder** [comment]
Hi @dowanx ,

Thank you so much for your feedback. :)

What you are asked, is really a very good question. I came up with  this ,

```css
.pretty>input[type='checkbox'][disabled]{
    cursor:default;
}
.pretty>input[type='checkbox'][disabled]+label{
    cursor:default;
    opacity:1;
}
.pretty>input[type='checkbox'][disabled]+label>i{
    cursor:not-allowed;
    opacity:0.5;
}
```
Let me know if that  helped! 
Thanks.

**Comment by lokesh-coder** [comment]
Hi @dowanx ,

I hope the above answer helped you. Closing now, but feel free to open again if you got any questions.

I have updated the repo to [version 3](https://github.com/lokesh-coder/pretty-checkbox/blob/master/README.md). 

For new version, the fix would be something like this,

```css
.pretty input[disabled] ~ * {
    opacity: inherit;
}
.pretty input[disabled] ~ .state label:after, 
.pretty input[disabled] ~ .state label:before{
    opacity:0.5
}
```

Thanks!
